export const INIT_REQUEST = "INIT_REQUEST";
export const INIT_SUCCESS = "INIT_SUCCESS";
export const INIT_FAILURE = "INIT_FAILURE";

export const SELECT_REQUEST = "SELECT_REQUEST";
export const SELECT_SUCCESS = "SELECT_SUCCESS";
export const SELECT_FAILURE = "SELECT_FAILURE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const THEME_UPDATE = "THEME_UPDATE";
