export const ENTITIES_FETCH_REQUEST = 'ENTITIES_FETCH_REQUEST';
export const ENTITIES_FETCH_SUCCESS = 'ENTITIES_FETCH_SUCCESS';
export const ENTITIES_FETCH_FAILURE = 'ENTITIES_FETCH_FAILURE';

export const FILTER_DAY_REQUEST = 'FILTER_DAY_REQUEST';
export const FILTER_DAY_SUCCESS = 'FILTER_DAY_SUCCESS';
export const FILTER_DAY_FAILURE = 'FILTER_DAY_FAILURE';

export const FILTER_CAMERA_REQUEST = 'FILTER_CAMERA_REQUEST';
export const FILTER_CAMERA_SUCCESS = 'FILTER_CAMERA_SUCCESS';
export const FILTER_CAMERA_FAILURE = 'FILTER_CAMERA_FAILURE';

export const SELECT_INITIAL_REQUEST = 'SELECT_INITIAL_REQUEST';
export const SELECT_INITIAL_SUCCESS = 'SELECT_INITIAL_SUCCESS';
export const SELECT_INITIAL_FAILURE = 'SELECT_INITIAL_FAILURE';

export const SELECT_DAY_REQUEST = 'SELECT_DAY_REQUEST';
export const SELECT_DAY_SUCCESS = 'SELECT_DAY_SUCCESS';
export const SELECT_DAY_FAILURE = 'SELECT_DAY_FAILURE';

export const SELECT_CAMERA_REQUEST = 'SELECT_CAMERA_REQUEST';
export const SELECT_CAMERA_SUCCESS = 'SELECT_CAMERA_SUCCESS';
export const SELECT_CAMERA_FAILURE = 'SELECT_CAMERA_FAILURE';

export const SELECT_ALL_REQUEST = 'SELECT_ALL_REQUEST';
export const SELECT_ALL_SUCCESS = 'SELECT_ALL_SUCCESS';
export const SELECT_ALL_FAILURE = 'SELECT_ALL_FAILURE';
